# Generated by Django 5.2.16 on 2026-09-28 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0030_alter_agentcardimpression_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReferralCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('window_hours', models.PositiveIntegerField(default=48)),
                ('required_paid_referrals', models.PositiveIntegerField(default=5)),
                ('reward_plan_slug', models.CharField(default='basic', max_length=50)),
                ('page_title', models.CharField(default='Event Registration', max_length=255)),
                ('page_instructions', models.TextField(blank=True, default='Register below to access your agent dashboard. Refer 5 agents who complete payment within 48 hours to unlock your Basic plan.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_referral_campaigns',
            },
        ),
        migrations.CreateModel(
            name='EventReferralParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('registered_at', models.DateTimeField()),
                ('deadline_at', models.DateTimeField(db_index=True)),
                ('window_hours', models.PositiveIntegerField()),
                ('required_paid_referrals', models.PositiveIntegerField()),
                ('reward_plan_slug', models.CharField(default='basic', max_length=50)),
                ('paid_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('blocked', 'Blocked')], db_index=True, default='active', max_length=20)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='event_referral_participant', to='agents.agent')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='event_referral.eventreferralcampaign')),
            ],
            options={
                'db_table': 'event_referral_participants',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='EventReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('registered', 'Registered'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('rejected', 'Rejected')], default='registered', max_length=20)),
                ('counts', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_name', models.CharField(blank=True, default='', max_length=255)),
                ('snapshot_email', models.CharField(blank=True, default='', max_length=255)),
                ('snapshot_mobile', models.CharField(blank=True, default='', max_length=50)),
                ('snapshot_city', models.CharField(blank=True, default='', max_length=255)),
                ('snapshot_plan', models.CharField(blank=True, default='', max_length=50)),
                ('snapshot_payment_status', models.CharField(blank=True, default='', max_length=50)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_agent', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='event_referral_attribution', to='agents.agent')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='event_referral.eventreferralparticipant')),
            ],
            options={
                'db_table': 'event_referral_referrals',
                'ordering': ['-registered_at'],
            },
        ),
    ]
