# Generated by Django 5.0.6 on 2026-07-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_test_traffic',
            field=models.BooleanField(default=False, help_text='Flag to exclude dev/QA sessions from analytics'),
        ),
    ]
