# Generated by Django 6.0.6 on 2026-07-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_is_test_traffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='agent_cards',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
