# Generated by Django 6.0.2 on 2026-07-06 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(default='About Us', max_length=255)),
                ('banner_subtitle', models.CharField(default='Connecting you with trusted insurance agents in your neighborhood', max_length=255)),
                ('who_we_are', models.TextField(blank=True)),
                ('why_we_exist', models.TextField(blank=True)),
                ('what_we_do', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('commitment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'About Page Settings',
                'verbose_name_plural': 'About Page Settings',
                'db_table': 'aboutpage_settings',
            },
        ),
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Ahmedabad - 380009 Gujarat, India', max_length=255)),
                ('email', models.CharField(default='support@padosiagent.com', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('map_iframe', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Page Settings',
                'verbose_name_plural': 'Contact Page Settings',
                'db_table': 'contactpage_settings',
            },
        ),
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_visible', models.BooleanField(default=True)),
                ('hero_headline', models.CharField(default='Find Trusted & Verified Insurance Experts in your Neighbourhood', max_length=255)),
                ('hero_subheadline', models.CharField(default='Connect with your local PadosiAgent', max_length=255)),
                ('hero_slide_1', models.CharField(default='Buy/Port/Renew Insurance', max_length=255)),
                ('dyk_visible', models.BooleanField(default=True, verbose_name='Did You Know Visible')),
                ('dyk_label', models.CharField(default='Did you know?', max_length=100)),
                ('dyk_title', models.CharField(default='Insights from the Padosi network', max_length=255)),
                ('quickpicks_visible', models.BooleanField(default=True, verbose_name='Quick Picks Visible')),
                ('quickpicks_label', models.CharField(default='Quick picks', max_length=100)),
                ('quickpicks_title', models.CharField(default='Also buy / renew shortcuts', max_length=255)),
                ('quickpicks_view_all_url', models.CharField(default='/find-agents?ServiceType=New%20Policy&openFilter=1', max_length=255)),
                ('quickpicks_view_all_text', models.CharField(default='View all products →', max_length=100)),
                ('why_choose_visible', models.BooleanField(default=True, verbose_name='Why Choose Visible')),
                ('why_choose_label', models.CharField(default='Why PadosiAgent', max_length=100)),
                ('why_choose_title', models.CharField(default="What makes PadosiAgent one of India's most trusted ways to buy insurance?", max_length=255)),
                ('why_choose_description', models.TextField(default='No spam, no platform fees and only licensed agents — built around your privacy, your time and your money.')),
                ('why_choose_button_url', models.CharField(default='/find-agents?openFilter=1', max_length=255)),
                ('why_choose_button_text', models.CharField(default='Find My PadosiAgent', max_length=100)),
                ('works_visible', models.BooleanField(default=True, verbose_name='How It Works Visible')),
                ('works_label', models.CharField(default='How It Works', max_length=100)),
                ('works_title', models.CharField(default='Find My PadosiAgent in 4 Simple Steps', max_length=255)),
                ('works_subtitle', models.TextField(default='From search to service - it takes just minutes for you')),
                ('testimonials_visible', models.BooleanField(default=True, verbose_name='Testimonials Visible')),
                ('testimonials_label', models.CharField(default='Testimonials', max_length=100)),
                ('testimonials_title', models.CharField(default='What Users Say About Their PadosiAgent', max_length=255)),
                ('testimonials_subtitle', models.TextField(default='Real experiences from users who found their PadosiAgent')),
            ],
            options={
                'verbose_name': 'Home Page Settings',
                'verbose_name_plural': 'Home Page Settings',
                'db_table': 'homepage_settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('review_text', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'testimonials',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('icon', models.CharField(default='search', max_length=50)),
                ('accent', models.CharField(default='accent-primary', max_length=50)),
                ('tooltip', models.CharField(blank=True, max_length=255, null=True)),
                ('badge', models.CharField(blank=True, max_length=10, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='home.homepagesettings')),
            ],
            options={
                'db_table': 'homepage_how_it_works_steps',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='InsightSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('icon', models.CharField(default='lightbulb', max_length=50)),
                ('accent', models.CharField(default='accent-rose', max_length=50)),
                ('bg', models.CharField(default='bg-rose-500', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='home.homepagesettings')),
            ],
            options={
                'db_table': 'homepage_insight_slides',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='QuickPickItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('icon', models.CharField(default='heart', max_length=50)),
                ('icon_bg', models.CharField(default='#fff1f2', max_length=50)),
                ('icon_color', models.CharField(default='#f43f5e', max_length=50)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('badge_bg', models.CharField(default='#ffe4e6', max_length=50)),
                ('badge_color', models.CharField(default='#be123c', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickpicks', to='home.homepagesettings')),
            ],
            options={
                'db_table': 'homepage_quick_picks',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(blank=True, max_length=50, null=True)),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('icon', models.CharField(default='shield-check', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_cards', to='home.homepagesettings')),
            ],
            options={
                'db_table': 'homepage_why_choose_cards',
                'ordering': ['sort_order'],
            },
        ),
    ]
