# Generated by Django 6.0.2 on 2026-07-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aboutpagesettings_contactpagesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DidYouKnowSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=150)),
                ('body', models.TextField(default='')),
                ('accent_class', models.CharField(default='', help_text='e.g., accent-rose', max_length=50)),
                ('bg_class', models.CharField(default='', help_text='e.g., bg-rose-500', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroProductTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=100)),
                ('icon', models.CharField(default='', max_length=50)),
                ('url', models.CharField(default='', max_length=255)),
                ('css_class', models.CharField(default='', help_text='e.g., pa-tile-rose', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='', max_length=50)),
                ('hero_text', models.CharField(default='', max_length=100)),
                ('tag', models.CharField(default='', max_length=100)),
                ('body', models.TextField(blank=True)),
                ('is_chart', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=100)),
                ('target', models.FloatField(default=0.0)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('icon', models.CharField(default='', max_length=50)),
                ('is_large', models.BooleanField(default=False)),
                ('is_decimal', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroTrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='', help_text='e.g., check-circle, shield', max_length=50)),
                ('label', models.CharField(default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='AboutPageSettings',
        ),
        migrations.DeleteModel(
            name='ContactPageSettings',
        ),
        migrations.RemoveField(
            model_name='insightslide',
            name='settings',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AlterModelOptions(
            name='howitworksstep',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='quickpickitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='whychoosecard',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='howitworksstep',
            old_name='accent',
            new_name='accent_class',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='dyk_visible',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_headline',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_slide_1',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_subheadline',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_visible',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='quickpicks_visible',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='testimonials_visible',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='why_choose_visible',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='works_visible',
        ),
        migrations.RemoveField(
            model_name='howitworksstep',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='howitworksstep',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='howitworksstep',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='howitworksstep',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='quickpickitem',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='quickpickitem',
            name='badge_bg',
        ),
        migrations.RemoveField(
            model_name='quickpickitem',
            name='badge_color',
        ),
        migrations.RemoveField(
            model_name='quickpickitem',
            name='icon_bg',
        ),
        migrations.RemoveField(
            model_name='quickpickitem',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='quickpickitem',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='whychoosecard',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='whychoosecard',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='whychoosecard',
            name='stat',
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_claims_card_heading',
            field=models.CharField(default='Claims, audits and policy review with local advisors', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_claims_card_label',
            field=models.CharField(default='FIND INSURANCE EXPERTS NEAR ME FOR:', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_claims_card_text',
            field=models.TextField(default='Easy local guidance from verified agents, with real advisor stories and trusted help just a few minutes away.'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_cta_claim_text',
            field=models.CharField(default='Insurance Claims Support', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_cta_claim_url',
            field=models.CharField(default='/find-agents?ServiceType=Claim%20Assistance&openFilter=1', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_cta_review_text',
            field=models.CharField(default='Insurance Audit', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_cta_review_url',
            field=models.CharField(default='/find-agents?ServiceType=Policy%20Review&openFilter=1', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_heading',
            field=models.CharField(default='Find a {Trusted} Insurance Expert in your {Padosi}', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_dyk',
            field=models.BooleanField(default=True, verbose_name='Show Did You Know Section'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_how_it_works',
            field=models.BooleanField(default=True, verbose_name='Show How It Works Section'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_quickpicks',
            field=models.BooleanField(default=True, verbose_name='Show Quick Picks Section'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_testimonials',
            field=models.BooleanField(default=True, verbose_name='Show Testimonials Section'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_why_choose',
            field=models.BooleanField(default=True, verbose_name='Show Why Choose Section'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='works_button_text',
            field=models.CharField(default='Find Agent', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='works_button_url',
            field=models.CharField(default='/find-agents?openFilter=1', max_length=255),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='badge_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quickpickitem',
            name='badge_bg_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quickpickitem',
            name='badge_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quickpickitem',
            name='badge_text_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quickpickitem',
            name='icon_bg_color',
            field=models.CharField(default='#fff1f2', max_length=20),
        ),
        migrations.AddField(
            model_name='quickpickitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whychoosecard',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whychoosecard',
            name='stat_text',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='testimonials_subtitle',
            field=models.CharField(default='Real experiences from users who found their PadosiAgent', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='works_subtitle',
            field=models.CharField(default='From search to service - it takes just minutes for you', max_length=255),
        ),
        migrations.AlterField(
            model_name='howitworksstep',
            name='icon',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='howitworksstep',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='howitworksstep',
            name='tooltip',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quickpickitem',
            name='icon',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='quickpickitem',
            name='icon_color',
            field=models.CharField(default='#f43f5e', max_length=20),
        ),
        migrations.AlterField(
            model_name='quickpickitem',
            name='label',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quickpickitem',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='whychoosecard',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='whychoosecard',
            name='caption',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='whychoosecard',
            name='icon',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='whychoosecard',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterModelTable(
            name='homepagesettings',
            table=None,
        ),
        migrations.AlterModelTable(
            name='howitworksstep',
            table=None,
        ),
        migrations.AlterModelTable(
            name='quickpickitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='whychoosecard',
            table=None,
        ),
        migrations.DeleteModel(
            name='InsightSlide',
        ),
    ]
