# Generated by Django 6.0.2 on 2026-06-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('fullname', models.CharField(blank=True, default='', max_length=70)),
                ('mobile', models.CharField(blank=True, default='', max_length=15)),
                ('agent_pincode', models.CharField(blank=True, default='', max_length=6)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('experience_range', models.CharField(blank=True, default='', max_length=50)),
                ('segments', models.JSONField(blank=True, default=list)),
                ('promo_code', models.CharField(blank=True, default='', max_length=30)),
                ('insurance_companies', models.JSONField(blank=True, default=list)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('client_base', models.CharField(blank=True, default='', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='agent_photos/')),
                ('about', models.TextField(blank=True, default='')),
                ('languages', models.JSONField(blank=True, default=list)),
                ('certifications', models.CharField(blank=True, default='', max_length=200)),
                ('license_number', models.CharField(blank=True, default='', max_length=255)),
                ('pan_number', models.CharField(blank=True, default='', max_length=20)),
                ('life_insurance', models.IntegerField(blank=True, null=True)),
                ('health_insurance', models.IntegerField(blank=True, null=True)),
                ('general_insurance', models.IntegerField(blank=True, null=True)),
                ('motor', models.IntegerField(blank=True, null=True)),
                ('desired_services', models.JSONField(blank=True, default=list)),
                ('software_services', models.JSONField(blank=True, default=list)),
                ('software_name', models.CharField(blank=True, default='', max_length=255)),
                ('registration_step', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_drafts',
                'ordering': ['-created_at'],
            },
        ),
    ]
