# Generated by Django 5.2.16 on 2026-09-28 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0029_agent_sub_distributor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcardimpression',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_impressions', to='agents.agent'),
        ),
    ]
