# Generated by Django 6.0.2 on 2026-07-08 14:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'admins',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=255)),
                ('model_type', models.CharField(blank=True, max_length=100, null=True)),
                ('model_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'admin_activity_logs',
            },
        ),
        migrations.CreateModel(
            name='AdminBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target', models.CharField(max_length=50)),
                ('channels', models.CharField(max_length=255)),
                ('sent_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_broadcasts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('replied', 'Replied'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PincodeImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('selected_states', models.JSONField(blank=True, null=True)),
                ('selected_districts', models.JSONField(blank=True, null=True)),
                ('available_states', models.JSONField(blank=True, null=True)),
                ('failed_details', models.JSONField(blank=True, null=True)),
                ('imported_by', models.CharField(blank=True, max_length=150, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pincode_import_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SecurityThreatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('event_type', models.CharField(max_length=255)),
                ('url', models.TextField(blank=True, null=True)),
                ('payload', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('hacker_name', models.CharField(blank=True, max_length=191, null=True)),
                ('hacker_email', models.CharField(blank=True, max_length=191, null=True)),
                ('hacker_mobile', models.CharField(blank=True, max_length=191, null=True)),
                ('location', models.CharField(blank=True, max_length=191, null=True)),
                ('isp', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'security_threat_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=191)),
                ('email', models.CharField(max_length=191, unique=True)),
                ('password', models.CharField(max_length=191)),
                ('custom_invite_message', models.TextField(blank=True, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(max_length=11)),
                ('status', models.CharField(max_length=9)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clicks', models.IntegerField(default=0)),
                ('total_referrals', models.IntegerField(default=0)),
                ('pending_referrals', models.IntegerField(default=0)),
                ('reward_discount_percent', models.IntegerField(default=0)),
                ('reward_claimed', models.BooleanField(default=False)),
                ('reward_type', models.CharField(blank=True, max_length=255, null=True)),
                ('reward_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_codes', to='agents.agent')),
                ('distributor', models.ForeignKey(blank=True, db_column='distributor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_referral_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referral_codes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReferralUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('referred_agent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('referred_agent_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('signed_up_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(blank=True, db_column='distributor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_referrals', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.ForeignKey(db_column='referral_code_id', on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='admin_panel.referralcode')),
                ('referred_agent', models.ForeignKey(blank=True, db_column='referred_agent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_usage_record', to='agents.agent')),
                ('referrer_agent', models.ForeignKey(blank=True, db_column='referrer_agent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_sent', to='agents.agent')),
            ],
            options={
                'db_table': 'referral_usages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AgentServicePincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_pincode', models.CharField(max_length=10)),
                ('city_name', models.CharField(max_length=150)),
                ('selected_areas_json', models.JSONField(blank=True, null=True)),
                ('postal_data_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicePincodes', to='agents.agent')),
            ],
            options={
                'db_table': 'agent_service_pincodes',
                'managed': True,
                'unique_together': {('agent', 'service_pincode')},
            },
        ),
    ]
