# Generated by Django 6.0.6 on 2026-06-30 05:54

from django.db import migrations


def create_table(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
            CREATE TABLE agent_service_pincodes (
                id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                agent_id BIGINT UNSIGNED NOT NULL,
                service_pincode VARCHAR(10) NOT NULL,
                city_name VARCHAR(150) NOT NULL,
                postal_data_json JSON NOT NULL,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                CONSTRAINT fk_agent_service_pincodes_agent FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
                UNIQUE KEY uk_agent_service_pincode (agent_id, service_pincode),
                INDEX idx_agent_id (agent_id),
                INDEX idx_service_pincode (service_pincode)
            );
            """)

def drop_table(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("DROP TABLE IF EXISTS agent_service_pincodes;")


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_agent_backup_trigger'),
    ]

    operations = [
        migrations.RunPython(create_table, reverse_code=drop_table),
    ]
