# Generated by Django 6.0.6 on 2026-06-30 07:33

from django.db import migrations


def add_column(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE agent_service_pincodes 
                ADD COLUMN selected_areas_json JSON NULL;
            """)

def drop_column(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE agent_service_pincodes 
                DROP COLUMN selected_areas_json;
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_agent_service_pincodes'),
    ]

    operations = [
        migrations.RunPython(add_column, reverse_code=drop_column),
    ]
