"""
Django settings for padosiagent project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / '.env', override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# ─── Core Security ──────────────────────────────────────────────────────────
# In production: set SECRET_KEY in environment variable, never commit it.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-u5n+gf_rt4&sgf%p8atp)#=b*129@9tyqfi)sz6v46nyd@+796'
)

# DEBUG must be False in production. Controlled via .env
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

# In production: set ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com in .env
_allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()] or ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://catfish-rebirth-uproar.ngrok-free.dev',
    'https://*.ngrok-free.dev',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://127.0.0.1:1234',
    'http://localhost:1234',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Internal Apps
    'apps.home',
    'apps.admin_panel',
    'apps.agents',
    'rest_framework',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.admin_panel.middleware.ThreatMonitorMiddleware',
    'apps.admin_panel.middleware.AdminIpWhitelistMiddleware',
    'apps.admin_panel.middleware.AdminPermissionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'padosi_agent.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.admin_panel.context_processors.admin_badge_counts',
                'apps.home.context_processors.footer_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'padosi_agent.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'padosiagent',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Cache
# https://docs.djangoproject.com/en/6.0/ref/settings/#cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': BASE_DIR / 'cache',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─── Brevo (Sendinblue) Transactional Email — PRIMARY ───────────────────────
# All values read from .env (dev) or environment variables (production).
# BREVO_API_KEY: your Brevo API key from https://app.brevo.com/settings/keys/api
BREVO_API_KEY       = os.environ.get('BREVO_API_KEY', '')       # Required for email
BREVO_FROM_EMAIL    = os.environ.get('BREVO_FROM_EMAIL', os.environ.get('MAIL_FROM_ADDRESS', 'noreply@padosiagent.com'))
BREVO_FROM_NAME     = os.environ.get('BREVO_FROM_NAME', os.environ.get('MAIL_FROM_NAME', 'PadosiAgent'))
# BREVO_OTP_FALLBACK: if True, allow registration to proceed even if email fails
# Set to False in production to strictly require email delivery.
BREVO_OTP_FALLBACK  = os.environ.get('BREVO_OTP_FALLBACK', 'true').lower() in ('true', '1', 'yes')

# ─── Django SMTP — FALLBACK (if Brevo API fails) ────────────────────────────
# Brevo SMTP relay: smtp-relay.brevo.com:587 (TLS) or :465 (SSL)
# Alternatively use Gmail, Mailgun, SendGrid SMTP, etc.
EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = os.environ.get('MAIL_HOST', 'smtp-relay.brevo.com')
EMAIL_PORT          = int(os.environ.get('MAIL_PORT', 587))
EMAIL_HOST_USER     = os.environ.get('MAIL_USERNAME', '')       # Brevo login email
EMAIL_HOST_PASSWORD = os.environ.get('MAIL_PASSWORD', '')       # Brevo SMTP key
_mail_enc           = os.environ.get('MAIL_ENCRYPTION', 'tls').lower()
EMAIL_USE_TLS       = _mail_enc == 'tls'
EMAIL_USE_SSL       = _mail_enc == 'ssl'
EMAIL_TIMEOUT       = 20
DEFAULT_FROM_EMAIL  = (
    f"{os.environ.get('MAIL_FROM_NAME', 'PadosiAgent')} "
    f"<{os.environ.get('MAIL_FROM_ADDRESS', 'noreply@padosiagent.com')}>"
)

# ─── Razorpay Payments ───────────────────────────────────────────────────────
RAZORPAY_KEY            = os.environ.get('RAZORPAY_KEY', '')
RAZORPAY_SECRET         = os.environ.get('RAZORPAY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = os.environ.get('RAZORPAY_WEBHOOK_SECRET', '')

# ─── Firebase Cloud Messaging (FCM) ─────────────────────────────────────────
FCM_API_KEY              = os.environ.get('FCM_API_KEY', '')
FCM_AUTH_DOMAIN          = os.environ.get('FCM_AUTH_DOMAIN', '')
FCM_PROJECT_ID           = os.environ.get('FCM_PROJECT_ID', '')
FCM_STORAGE_BUCKET       = os.environ.get('FCM_STORAGE_BUCKET', '')
FCM_MESSAGING_SENDER_ID  = os.environ.get('FCM_MESSAGING_SENDER_ID', '')
FCM_APP_ID               = os.environ.get('FCM_APP_ID', '')
FCM_VAPID_KEY            = os.environ.get('FCM_VAPID_KEY', '')
FCM_SERVICE_ACCOUNT_JSON = os.environ.get('FCM_SERVICE_ACCOUNT_JSON', '')

# ─── Google OAuth ────────────────────────────────────────────────────────────
GOOGLE_CLIENT_ID     = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
GOOGLE_REDIRECT_URI  = os.environ.get('GOOGLE_REDIRECT_URI', '')

# ─── Logging ─────────────────────────────────────────────────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} — {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'apps': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

TEST_RUNNER = 'apps.home.test_runner.ManagedModelsTestRunner'

# ─── Production HTTP / SSL Hardening ─────────────────────────────────────────
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    
    # Enable HSTS for 1 year
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ─── Admin Access Controls ───────────────────────────────────────────────────
_whitelist_ips_env = os.environ.get('ADMIN_WHITELIST_IPS', '')
ADMIN_WHITELIST_IPS = [ip.strip() for ip in _whitelist_ips_env.split(',') if ip.strip()]



